---
title: "mymain"
author: "Ethan Cook"
date: "2023-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Libraries
```{r}
library(dplyr)
library(ggplot2)
#library(recommenderlab)
#library(DT)
library(data.table)
library(reshape2)
library(coop)
```


# Load Data
## Ratings Data (ratings)
```{r}
myurl = "https://liangfgithub.github.io/MovieData/"

# use colClasses = 'NULL' to skip columns
ratings = read.csv(paste0(myurl, 'ratings.dat?raw=true'), 
                   sep = ':',
                   colClasses = c('integer', 'NULL'), 
                   header = FALSE)
colnames(ratings) = c('UserID', 'MovieID', 'Rating', 'Timestamp')
```

## Movies Data (movies)
```{r}
movies = readLines(paste0(myurl, 'movies.dat?raw=true'))
movies = strsplit(movies, split = "::", fixed = TRUE, useBytes = TRUE)
movies = matrix(unlist(movies), ncol = 3, byrow = TRUE)
movies = data.frame(movies, stringsAsFactors = FALSE)
colnames(movies) = c('MovieID', 'Title', 'Genres')
movies$MovieID = as.integer(movies$MovieID)

# convert accented characters
movies$Title[73]
movies$Title = iconv(movies$Title, "latin1", "UTF-8")
movies$Title[73]

# extract year
movies$Year = as.numeric(unlist(
  lapply(movies$Title, function(x) substr(x, nchar(x)-4, nchar(x)-1))))
```

## User Data (users)
```{r}
users = read.csv(paste0(myurl, 'users.dat?raw=true'),
                 sep = ':', header = FALSE)
users = users[, -c(2,4,6,8)] # skip columns
colnames(users) = c('UserID', 'Gender', 'Age', 'Occupation', 'Zip-code')
```

## Ratings Matrix
```{r}
ratings_mat = read.csv("ratings_matrix.csv")
```

## STEP 1: Center Ratings Matrix 
```{r}
row_means = rowMeans(ratings_mat, na.rm=TRUE)
ratings_mat_centered = ratings_mat - row_means
```
## STEP 2: Cosine Similarity
```{r}
S = coop::cosine(as.matrix(ratings_mat_centered), use = "pairwise.complete.obs")
S = 0.5 + S/2
for (i in 1:nrow(S)) {
  S[i, i] = NA
  for (j in i:nrow(S)) {
    if ( length(intersect(which(!is.na(ratings_mat[,i])), which(!is.na(ratings_mat[,j])))) <= 2) {
      S[i, j] = NA
      S[j, i] = NA
    }
  }
}
write.csv(S, file="S_post_step2.csv")
```

## STEP 3: Top 30 only
```{r}
S_post_step2_ = read.csv("S_post_step2.csv")
S = S_post_step2_[,-1]
rownames(S) <- S_post_step2_[,1]

S[c("m1", "m10", "m100", "m1510", "m260", "m3212"), c("m1", "m10", "m100", "m1510", "m260", "m3212")]

for (r in 1:nrow(S)) {
  keep_idxs = order(as.matrix(S[r,]), decreasing=TRUE)[1:30]
  S[r,][-keep_idxs] = NA
}
write.csv(S, file="S_post_step3.csv")
```

!!!!
RUN CODE FROM HERE
!!!!

## STEP 4: myIBCF

```{r}
myIBCF = function(w) {
  S_post_step3_ = read.csv("S_post_step3.csv")
  S = S_post_step3_[,-1]
  rownames(S) <- S_post_step3_[,1]
  recom_rankings = list()
  for (col in colnames(S))
  {
    recom_rankings[[col]] = (sum(S[[col]] * w, na.rm=TRUE)) / sum(S[[col]] * !is.na(w), na.rm=TRUE)
  }
  recom_rankings
}

# Create test user who perfers animated movies
w_animated = rep(NA, 3706)
w_animated[1] = 5
w_animated[13] = 4
w_animated[48] = 5
w_animated[239] = 4
w_animated[244] = 4
w_animated[313] = 5
w_animated[558] = 4
w_animated[17] = 5
w_animated[89] = 4
w_animated[99] = 3
w_animated[230] = 4
w_animated[247] = 4
w_animated[311] = 5
w_animated[2303] = 4
w_animated[2] = 1
w_animated[3] = 2
w_animated[4] = 1
w_animated[5] = 2
w_animated[6] = 3
```

```{r}
#returned_rankings = myIBCF(w_animated) # run this for a much shorter computation time
returned_rankings = myIBCF(ratings_mat[1181,]) # Why does this take forever..? Is this definitely user 1181..?
non_na_ranks = returned_rankings[!is.na(returned_rankings)]
head(non_na_ranks[order(-unlist(non_na_ranks))], n=100)

```

```{r}
S_post_step3_ = read.csv("S_post_step3.csv")
S = S_post_step3_[,-1]
rownames(S) <- S_post_step3_[,1]
var = data.frame(row.names = rownames(S))

for (col in colnames(S))
{
  var[[col]] = sum(S[[col]] * w_animated, na.rm=TRUE)
  if (sum(var[[col]]) != 0)
  {
    print(sum(var[[col]]))
  }
}
```





