---
title: "Project1"
author: "Ethan Cook"
date: "2023-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# TODO
train = read.csv("fold1/train.csv")
test = read.csv("fold1/test.csv") 
```

```{r}
calc_RMSE = function(predictions, actuals)
{
  sqrt(mean((predictions - actuals) ^ 2))
}

```

```{r}
mod = lm (Sale_Price ~ Overall_Cond + Fence + Kitchen_Qual + Fireplaces + Full_Bath, data = train)
calc_RMSE(mod$fitted.values, train$Sale_Price)
```

```{r}
train = subset(train, select = -c(Street, Utilities, Condition_2, Roof_Matl, Heating, Pool_QC, Misc_Feature, Low_Qual_Fin_SF, Pool_Area, Longitude, Latitude) )
```

```{r}
library(DescTools)

train$Lot_Frontage = Winsorize(train$Lot_Frontage, minval = 0)
train$Lot_Area = Winsorize(train$Lot_Area, minval = 0)
train$Mas_Vnr_Area = Winsorize(train$Mas_Vnr_Area, minval = 0)
train$BsmtFin_SF_2 = Winsorize(train$BsmtFin_SF_2, minval = 0)
train$Bsmt_Unf_SF = Winsorize(train$Bsmt_Unf_SF, minval = 0)
train$Total_Bsmt_SF = Winsorize(train$Total_Bsmt_SF, minval = 0)
train$Second_Flr_SF = Winsorize(train$Second_Flr_SF, minval = 0)
train$First_Flr_SF = Winsorize(train$First_Flr_SF, minval = 0)
train$Gr_Liv_Area = Winsorize(train$Gr_Liv_Area, minval = 0)
train$Garage_Area = Winsorize(train$Garage_Area, minval = 0)
train$Wood_Deck_SF = Winsorize(train$Wood_Deck_SF, minval = 0)
train$Open_Porch_SF = Winsorize(train$Open_Porch_SF, minval = 0)
train$Enclosed_Porch = Winsorize(train$Enclosed_Porch, minval = 0)
train$Three_season_porch = Winsorize(train$Three_season_porch, minval = 0)
train$Screen_Porch = Winsorize(train$Screen_Porch, minval = 0)
train$Misc_Val = Winsorize(train$Misc_Val, minval = 0)
```

```{r}
train.x = subset(train, select = -c(PID, Sale_Price) ) # train data without "PID" and "Sale_Price"
train.y = log(train$Sale_Price) # log transformed "Sale_Price"

# replace missing by zero
train.x$Garage_Yr_Blt[is.na(train.x$Garage_Yr_Blt)] = 0

categorical.vars = colnames(train.x)[
  which(sapply(train.x,
                 function(x) mode(x)=="character"))]

train.matrix = train.x[, !colnames(train.x) %in% categorical.vars, 
                          drop=FALSE]

n.train = nrow(train.matrix)
for(var in categorical.vars){
    mylevels = sort(unique(train.x[, var]))
    m = length(mylevels)
    m = ifelse(m > 2, m, 1)
    tmp.train = matrix(0, n.train, m)
    col.names = NULL
    for(j in 1:m){
      tmp.train[train.x[, var]==mylevels[j], j] = 1
      col.names = c(col.names, paste(var, '_', mylevels[j], sep=''))
      }
    colnames(tmp.train) = col.names
    train.matrix = cbind(train.matrix, tmp.train)
}
train.matrix = train.matrix[order(names(train.matrix))]
```



```{r, results = 'hide'}
require(xgboost)
dtrain <- xgb.DMatrix(data =data.matrix(train.matrix), label = data.matrix(train.y))
bstSparse <- xgboost(data = dtrain, eta=.05, subsample = .5 , nrounds=5000)
```

```{r}
test.x = subset(test, select = -c(PID) ) # train data without "PID" and "Sale_Price"
 # log transformed "Sale_Price"

# replace missing by zero
test.x$Garage_Yr_Blt[is.na(test.x$Garage_Yr_Blt)] = 0

categorical.vars = colnames(test.x)[
  which(sapply(test.x,
                 function(x) mode(x)=="character"))]

test.matrix = test.x[, !colnames(test.x) %in% categorical.vars, 
                          drop=FALSE]

n.test = nrow(test.matrix)
for(var in categorical.vars){
    mylevels = sort(unique(test.x[, var]))
    m = length(mylevels)
    m = ifelse(m > 2, m, 1)
    tmp.test = matrix(0, n.test, m)
    col.names = NULL
    for(j in 1:m){
      tmp.test[test.x[, var]==mylevels[j], j] = 1
      col.names = c(col.names, paste(var, '_', mylevels[j], sep=''))
      }
    colnames(tmp.test) = col.names
    test.matrix = cbind(test.matrix, tmp.test)
}

testonly <- setdiff(colnames(test.matrix), colnames(train.matrix))
trainonly <- setdiff(colnames(train.matrix), colnames(test.matrix))

df = data.frame(matrix(0, nrow = dim(test.matrix)[1], ncol = length(trainonly))) 
colnames(df) = trainonly

all_columns = cbind(test.matrix, df)
test.matrix = all_columns[ , !(names(all_columns) %in% testonly)]

test.matrix = test.matrix[order(names(test.matrix))]
```

```{r}
dtest <- xgb.DMatrix(data = data.matrix(test.matrix))
pred_y = round(exp(predict(bstSparse, dtest)), 1)
```

```{r}
idxs = 1:length(pred_y)
pids = train$PID
file_strings = sapply(idxs, function(idx) {paste(pids[idx], pred_y[idx], sep= ", ")} )
fileConn <- file("submission1.txt")
file_strings = c("PID, Sale_Price", file_strings)
writeLines(file_strings, fileConn)
close(fileConn)
```





